export const ASHANAS_GET = 'ASHANAS_GET';
export const ASHANAS_FILTER = 'ASHANAS_FILTER';
export const SEQUENCE_SET = 'SEQUENCE_SET';
export const SEQUENCE_ADD_ASHANA = 'SEQUENCE_ADD_ASHANA';
export const SEQUENCE_SAVED = 'SEQUENCE_SAVE';
export const SEQUENCE_ERROR_SAVING = 'SEQUENCE_ERROR_SAVING';
export const SEQUENCE_GET_ALL = 'SEQUENCE_GET_ALL';
